services:
  app:
    image: cyberorca/orca-server:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_app
    restart: unless-stopped
    ports:
      - "80:8000"
    volumes:
      - .:/app
    environment:
      APP_ENV: local
    command: php artisan octane:start --server=frankenphp --host=0.0.0.0 --port=8000
